### ISSUE TITLE
Create a hook for sending a toast

### ISSUE THREAD

**Issue by kharann** [dotkom/monoweb#160]
## Is your feature request related to a problem? Please describe.

Currently, there's no way to send a toast.

## Describe the solution you'd like

A hook that includes that gives you a function to send a toast when called. I believe that using a library such as 
https://react-hot-toast.com/ would be beneficial.

## Additional context

Probably use the library, and style the toast to the one we currently have

**Comment by Thomhas** [comment]
@kharann you showed me how to code, now I hate myself.
