### ISSUE TITLE
"Coming events" list item

### ISSUE THREAD

**Issue by kharann** [dotkom/monoweb#165]
https://www.figma.com/file/Pmw8euC6L6fHbh6mmLLeUX/Mainpage?node-id=0%3A1

**Comment by kharann** [comment]
@matsjla Assign someone to this

![Image](https://user-images.githubusercontent.com/41551253/191544195-6206e11f-8183-49f0-b966-ce66b6cacd9a.png)

**Comment by matsjla** [comment]
Have fun @jotjern
