### ISSUE TITLE
Determine authorization library

### ISSUE THREAD

**Issue by kharann** [dotkom/monoweb#223]
Onlineweb has a complex system of authorization. There's a lot of different cases in onlineweb and requires a lot of logic.

- RBAC (role based could be valid as comittes has different perms)
- PBAC (policy could be nice)

- Alternatives:
    - OPA?
    - casbin?
    - casl?

**Comment by hsluoyz** [comment]
@kharann you can try: https://github.com/casbin/node-casbin, it supports all of PBAC, RBAC and ABAC
