### ISSUE TITLE
Domain: Article

### ISSUE THREAD

**Issue by kharann** [dotkom/monoweb#97]
# Core API
- [x] Create a module for article 
- [x] Create a repository which uses the sanity client to fetch data from sanity
- [x] Create a service which allows the users the retrieve articles by slug, id and the latest 5 articles.
- [x] Create a graphql resolver which uses article service and returns the desired data
- [ ] Look into wtf to do with Portable Text. Honestly maybe we should just switch to Markdown for articles
- [ ] add filtering (tags, date, title) and sort (date, title) in the service
- [ ] make tests for filtering and sort

**Comment by Thomhas** [comment]
This is part of the development before the migration to the monorepo. So it is deprecated
